### ISSUE TITLE
using Orderable*Inline without OrderableAdmin as parent does not include js files

### ISSUE THREAD

**Issue by proppy** [tkaemming/django-orderable#2]
Hi,

I believe this is because inlines are not registered in the admin.site.

Let me know if you need more information.

**Comment by tkaemming** [comment]
I couldn't replicate this issue — if you change the BookAdmin model in orderable/tests/admin.py to admin.ModelAdmin, the JavaScript is still loaded by the Media definition on the base OrderableInline (see orderable/admin.py).

I'd love to help If you can provide more details on the issue, but right now there's not much I can do.
